# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimeKeeper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimeKeeper
	pod 'SwiftLint'
    pod 'Alamofire', '~> 4.3'
    pod 'SwiftyJSON'
    pod 'MBProgressHUD'
    
    pod 'CollapsibleTableSectionViewController', '~> 1.0.0'
    pod 'SideMenu'
end
